# Generated by Django 4.2.27 on 2026-01-01 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_alter_trackinghistory_current_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackinghistory',
            name='current_balance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tracker.currentbalance'),
        ),
    ]
