# Generated by Django 4.2.27 on 2026-01-01 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_alter_trackinghistory_current_balance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trackinghistory',
            old_name='expense',
            new_name='expense_type',
        ),
        migrations.AlterField(
            model_name='trackinghistory',
            name='amount',
            field=models.FloatField(default=0.0),
        ),
    ]
