# Generated by Django 4.2.27 on 2026-01-09 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_rename_expense_trackinghistory_expense_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackinghistory',
            name='amount',
            field=models.FloatField(default=0.0, editable=False),
        ),
    ]
